services:
  server:
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
      - ./server/logs:/app/logs
    command: ["npm", "run", "dev"]

  client:
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

  database:
    ports:
      - "5432:5432" 