services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    container_name: wwii_scanner_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8663
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - wwii_network_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Don't expose database port in production for security
    # ports:
    #   - "5432:5432"

  # Node.js Backend Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: production
    container_name: wwii_scanner_server_prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:8663@database:5432/mydb
      GOOGLE_CREDENTIALS_PATH: ./src/config/service-account-key.json
      GOOGLE_DRIVE_FOLDER_ID: 1UYj9HKZOrkJkN5B1ssqX3_3CZELo02Bp
      GROQ_API_KEY: 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
      JWT_SECRET: your-super-secret-jwt-key-here-make-it-long-and-random
    volumes:
      - ./server/logs:/app/logs
    networks:
      - wwii_network_prod
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Don't expose server port directly in production
    # ports:
    #   - "5000:5000"

  # React Frontend Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    container_name: wwii_scanner_client_prod
    restart: unless-stopped
    networks:
      - wwii_network_prod
    depends_on:
      - server
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: wwii_scanner_nginx_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - wwii_network_prod
    depends_on:
      - client
      - server
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  wwii_network_prod:
    driver: bridge
    name: wwii_scanner_network_prod

volumes:
  postgres_data_prod:
    name: wwii_scanner_postgres_data_prod 